### ISSUE TITLE
[New Scope] Add "Expected By" field to Shipment Creation

### ISSUE THREAD

**Issue by navarr** [meanbee/gmailactions#6]
As a customer, I want to know when I can expect my package.

Right now this extension defaults to an expected date of a year from now and hopes that Google will check the tracking code and update the expected arrival date of it's own volition.  This isn't the best experience.

For completion of this ticket:
- When adding a shipment the admin should be able to specify the **latest date the package will arrive by**
- This date should be added to [Shipment.php L36](https://github.com/meanbee/gmailactions/blob/9a4ac58d73cadcdc435d15907e7685baaac87b13/code/Block/Shipment.php#L36)

For additional points:
- When adding a shipment the admin should be able to specify the **earliest date the package will arrive by**
- This date should be added to the array in [Shipment.php around L36](https://github.com/meanbee/gmailactions/blob/9a4ac58d73cadcdc435d15907e7685baaac87b13/code/Block/Shipment.php#L36) - It's key should be _expectedArrivalFrom_.

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
