### ISSUE TITLE
CooL! is this code still maintained? working M1.9.2.3?

### ISSUE THREAD

**Issue by seansan** [meanbee/gmailactions#8]
CooL! is this code still maintained? working M1.9.2.3?

**Comment by navarr** [comment]
I imagine if you have a contribution you can tweet at meanbee if its not noticed right away, but I don't think it's actively being developed at this time.

I am unsure there is any reason for it not to work in M1.9.2.3, but you'll have to test it yourself to check.

**Comment by bobbyshaw** [comment]
What @navarr said :)

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
